import './globals.css'
import common from './styles/common.module.css'
import type { Metadata } from 'next'
import {AuthProvider} from "../Providers"
import NavBarAdmin from '@/components/Admin/NavBarAdminMobile'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ShantiSpace',
  description: 'Generated by create next app',
  keywords: 'йога, реабілітація'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body className={inter.className}>
        {/* <AuthProvider> */}
        <NavBar/>
          <div className='mx-auto min-[-320px]:px-2 sm:px-4 md:px-6 lg:px-8 xl:px-10'>
      
            {children}
          </div>
        {/* </AuthProvider> */}
      </body>
    </html>
  )
}
