import './globals.css'
import common from './styles/common.module.css'
import type { Metadata } from 'next'
import NavBarAdmin from '@/components/Admin/NavBarAdmin'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ShantiSpace',
  description: 'Generated by create next app',
  keywords: 'йога, реабілітація'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body className={inter.className}>
        <div className={common.containerMy}>
          <NavBarAdmin />
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  )
}
